apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: skitt-prod
type: Opaque
stringData:
  # For local PostgreSQL in Kubernetes
  DB_HOST: "postgres"  # Service name in Kubernetes
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  # For AWS RDS (use this instead when deploying to cloud)
  # DB_HOST: "database-1.cbgim4yu6fan.eu-north-1.rds.amazonaws.com"
  # DB_PORT: "5432"
  # DB_NAME: "postgres"
  # DB_USER: "postgres"
  # DB_PASSWORD: "postgres"
